\c recipes_db;
INSERT INTO recipes (
  name, 
  ingredients, 
  instructions, 
  preparation_time, 
  cooking_time, 
  total_time, 
  servings, 
  calories_per_serving, 
  protein, 
  carbohydrates, 
  fat,
  imageurl,
  category,
  origin
)
VALUES 
  (
    'Spaghetti Carbonara', 
    '[
      {"ingredient": "spaghetti", "amount": "200g"},
      {"ingredient": "eggs", "amount": "2"},
      {"ingredient": "bacon", "amount": "100g, diced"},
      {"ingredient": "parmesanCheese", "amount": "50g, grated"},
      {"ingredient": "blackPepper", "amount": "to taste"}
    ]'::jsonb, 
    '[
      "Cook spaghetti according to package instructions.",
      "Meanwhile, fry bacon until crispy.",
      "Whisk eggs, Parmesan cheese, and black pepper in a bowl.",
      "Drain spaghetti, reserving some cooking water.",
      "Combine hot spaghetti with bacon and egg mixture, tossing quickly."
    ]'::jsonb, 
    '10 minutes', 
    '15 minutes', 
    '25 minutes', 
    '4', 
    '400', 
    '20g', 
    '50g', 
    '15g',
    'https://static01.nyt.com/images/2021/02/14/dining/carbonara-horizontal/carbonara-horizontal-square640-v2.jpg',
    'Pasta',
    'Italian'
  ),
  (
    'Chicken Stir-Fry', 
    '[
      {"ingredient": "chickenBreast", "amount": "400g, thinly sliced"},
      {"ingredient": "broccoli", "amount": "1 head, chopped"},
      {"ingredient": "bellPepper", "amount": "1, sliced"},
      {"ingredient": "soySauce", "amount": "3 tbsp"},
      {"ingredient": "garlic", "amount": "3 cloves, minced"},
      {"ingredient": "ginger", "amount": "1 tsp, grated"},
      {"ingredient": "vegetableOil", "amount": "2 tbsp"}
    ]'::jsonb, 
    '[
      "Heat vegetable oil in a large pan or wok over medium-high heat.",
      "Add garlic and ginger, stir-fry for 30 seconds.",
      "Add chicken slices, stir-fry until cooked through.",
      "Add broccoli and bell pepper, stir-fry until tender-crisp.",
      "Stir in soy sauce, cook for another minute.",
      "Serve hot."
    ]'::jsonb, 
    '15 minutes', 
    '15 minutes', 
    '30 minutes', 
    '4', 
    '300', 
    '30g', 
    '15g', 
    '10g',
    'https://www.saltandlavender.com/wp-content/uploads/2022/03/chicken-stir-fry-1.jpg',
    'Main Courses',
    'Chinese'
  ),
  (
    'Classic Beef Lasagna', 
    '[
      {"ingredient": "lasagnaNoodles", "amount": "250g"},
      {"ingredient": "groundBeef", "amount": "500g"},
      {"ingredient": "onion", "amount": "1, chopped"},
      {"ingredient": "garlic", "amount": "2 cloves, minced"},
      {"ingredient": "tomatoSauce", "amount": "700ml"},
      {"ingredient": "mozzarellaCheese", "amount": "200g, grated"},
      {"ingredient": "ricottaCheese", "amount": "250g"},
      {"ingredient": "parmesanCheese", "amount": "50g, grated"},
      {"ingredient": "driedOregano", "amount": "1 tsp"},
      {"ingredient": "salt", "amount": "to taste"},
      {"ingredient": "pepper", "amount": "to taste"}
    ]'::jsonb, 
    '[
      "Preheat oven to 180°C (350°F).",
      "Cook lasagna noodles according to package instructions.",
      "In a large skillet, cook ground beef, onion, and garlic until beef is browned.",
      "Stir in tomato sauce, dried oregano, salt, and pepper. Simmer for 10 minutes.",
      "In a greased baking dish, layer noodles, meat sauce, ricotta cheese, and mozzarella cheese. Repeat layers.",
      "Top with grated Parmesan cheese.",
      "Bake in preheated oven for 30 minutes, until hot and bubbly.",
      "Let stand for 10 minutes before serving."
    ]'::jsonb, 
    '30 minutes', 
    '30 minutes', 
    '1 hour', 
    '6', 
    '500', 
    '35g', 
    '40g', 
    '20g',
    'https://www.recipegirl.com/wp-content/uploads/2021/04/Classic-Beef-Lasagna-8.jpeg',
    'Pasta',
    'Italian'
  ),
  (
    'Caesar Salad', 
    '[
      {"ingredient": "romaineLettuce", "amount": "1 head, torn into bite-size pieces"},
      {"ingredient": "croutons", "amount": "1 cup"},
      {"ingredient": "parmesanCheese", "amount": "50g, grated"},
      {"ingredient": "lemonJuice", "amount": "2 tbsp"},
      {"ingredient": "worcestershireSauce", "amount": "1 tsp"},
      {"ingredient": "dijonMustard", "amount": "1 tsp"},
      {"ingredient": "garlic", "amount": "1 clove, minced"},
      {"ingredient": "oliveOil", "amount": "3 tbsp"},
      {"ingredient": "salt", "amount": "to taste"},
      {"ingredient": "blackPepper", "amount": "to taste"}
    ]'::jsonb, 
    '[
      "In a large salad bowl, whisk together lemon juice, Worcestershire sauce, Dijon mustard, garlic, olive oil, salt, and black pepper.",
      "Add torn romaine lettuce and toss to coat.",
      "Top with grated Parmesan cheese and croutons.",
      "Serve immediately."
    ]'::jsonb, 
    '15 minutes', 
    '0 minutes', 
    '15 minutes', 
    '4', 
    '250', 
    '8g', 
    '15g', 
    '18g',
    'https://natashaskitchen.com/wp-content/uploads/2019/01/Caesar-Salad-Recipe-3.jpg',
    'Salad',
    'Italian'
  ),
  (
    'Chocolate Chip Cookies', 
    '[
      {"ingredient": "butter", "amount": "200g, softened"},
      {"ingredient": "brownSugar", "amount": "200g"},
      {"ingredient": "granulatedSugar", "amount": "100g"},
      {"ingredient": "eggs", "amount": "2"},
      {"ingredient": "vanillaExtract", "amount": "2 tsp"},
      {"ingredient": "allPurposeFlour", "amount": "300g"},
      {"ingredient": "bakingSoda", "amount": "1 tsp"},
      {"ingredient": "salt", "amount": "1/2 tsp"},
      {"ingredient": "chocolateChips", "amount": "300g"}
    ]'::jsonb, 
    '[
      "Preheat oven to 180°C (350°F).",
      "In a large bowl, cream together butter, brown sugar, and granulated sugar until smooth.",
      "Beat in eggs and vanilla extract until fluffy.",
      "Combine flour, baking soda, and salt; gradually stir into the creamed mixture.",
      "Stir in chocolate chips.",
      "Drop by rounded teaspoonfuls onto ungreased cookie sheets.",
      "Bake for 10 to 12 minutes in preheated oven, or until edges are golden brown.",
      "Allow cookies to cool on baking sheet for 5 minutes before transferring to a wire rack to cool completely."
    ]'::jsonb, 
    '20 minutes', 
    '10 minutes', 
    '30 minutes', 
    '36 cookies', 
    '150', 
    '2g', 
    '20g', 
    '7g',
    'https://sallysbakingaddiction.com/wp-content/uploads/2013/05/classic-chocolate-chip-cookies.jpg',
    'Desserts',
    'American'
  ),
  (
    'Vegetarian Chili', 
    '[
      {"ingredient": "kidneyBeans", "amount": "400g can, drained and rinsed"},
      {"ingredient": "blackBeans", "amount": "400g can, drained and rinsed"},
      {"ingredient": "onion", "amount": "1, chopped"},
      {"ingredient": "bellPepper", "amount": "1, chopped"},
      {"ingredient": "carrots", "amount": "2, diced"},
      {"ingredient": "garlic", "amount": "2 cloves, minced"},
      {"ingredient": "chiliPowder", "amount": "2 tbsp"},
      {"ingredient": "cumin", "amount": "1 tbsp"},
      {"ingredient": "paprika", "amount": "1 tsp"},
      {"ingredient": "dicedTomatoes", "amount": "800g can"},
      {"ingredient": "vegetableStock", "amount": "500ml"},
      {"ingredient": "oliveOil", "amount": "2 tbsp"},
      {"ingredient": "salt", "amount": "to taste"},
      {"ingredient": "blackPepper", "amount": "to taste"}
    ]'::jsonb, 
    '[
      "In a large pot, heat olive oil over medium heat.",
      "Add chopped onion, bell pepper, carrots, and garlic. Cook until softened, about 5 minutes.",
      "Stir in chili powder, cumin, and paprika. Cook for 1 minute until fragrant.",
      "Add diced tomatoes, vegetable stock, kidney beans, and black beans.",
      "Season with salt and pepper to taste.",
      "Bring to a boil, then reduce heat and simmer for 30 minutes, stirring occasionally.",
      "Serve hot, optionally garnished with sour cream, shredded cheese, and chopped cilantro."
    ]'::jsonb, 
    '15 minutes', 
    '45 minutes', 
    '1 hour', 
    '6', 
    '300', 
    '12g', 
    '50g', 
    '5g',
    'https://s23209.pcdn.co/wp-content/uploads/2022/10/211129_DAMN-DELICIOUS_Vegetarian-Chili_279.jpg',
    'Vegetarian',
    'Mexican'
  ),
  (
    'Margherita Pizza', 
    '[
      {"ingredient": "pizzaDough", "amount": "1 ball (store-bought or homemade)"},
      {"ingredient": "tomatoSauce", "amount": "200g"},
      {"ingredient": "freshMozzarellaCheese", "amount": "200g, sliced"},
      {"ingredient": "cherryTomatoes", "amount": "100g, halved"},
      {"ingredient": "freshBasilLeaves", "amount": "a handful"},
      {"ingredient": "oliveOil", "amount": "2 tbsp"},
      {"ingredient": "salt", "amount": "to taste"},
      {"ingredient": "blackPepper", "amount": "to taste"}
    ]'::jsonb, 
    '[
      "Preheat oven to the highest temperature setting (usually around 250°C or 480°F).",
      "Roll out pizza dough on a floured surface to desired thickness.",
      "Transfer dough to a pizza stone or baking sheet.",
      "Spread tomato sauce evenly over dough, leaving a small border around the edges.",
      "Arrange mozzarella slices and cherry tomato halves on top of sauce.",
      "Drizzle with olive oil and season with salt and black pepper.",
      "Bake in preheated oven for 10-12 minutes, until crust is golden and cheese is melted and bubbly.",
      "Remove from oven and top with fresh basil leaves before serving."
    ]'::jsonb, 
    '15 minutes', 
    '10 minutes', 
    '25 minutes', 
    '2-4', 
    '400', 
    '15g', 
    '45g', 
    '18g',
    'https://cookieandkate.com/images/2021/07/classic-margherita-pizza.jpg',
    'Baking',
    'Italian'
  )
  (
    'Spaghetti Carbonara', 
    '[{"ingredient": "spaghetti", "amount": "200g"},{"ingredient": "eggs", "amount": "2"},{"ingredient": "bacon", "amount": "100g, diced"},{"ingredient": "parmesanCheese", "amount": "50g, grated"},{"ingredient": "blackPepper", "amount": "to taste"}]'::jsonb, 
    '[{"instruction": "Cook spaghetti according to package instructions."},{"instruction": "Meanwhile, fry bacon until crispy."},{"instruction": "Whisk eggs, Parmesan cheese, and black pepper in a bowl."},{"instruction": "Drain spaghetti, reserving some cooking water."},{"instruction": "Combine hot spaghetti with bacon and egg mixture, tossing quickly."}]'::jsonb, 
    '10 minutes', 
    '15 minutes', 
    '25 minutes', 
    '4', 
    '400', 
    '20g', 
    '50g', 
    '15g',
    'https://static01.nyt.com/images/2021/02/14/dining/carbonara-horizontal/carbonara-horizontal-square640-v2.jpg',
    'Pasta',
    'Italian'
  ),
  (
    'Chicken Stir-Fry', 
    '[{"ingredient": "chickenBreast", "amount": "400g, thinly sliced"},{"ingredient": "broccoli", "amount": "1 head, chopped"},{"ingredient": "bellPepper", "amount": "1, sliced"},{"ingredient": "soySauce", "amount": "3 tbsp"},{"ingredient": "garlic", "amount": "3 cloves, minced"},{"ingredient": "ginger", "amount": "1 tsp, grated"},{"ingredient": "vegetableOil", "amount": "2 tbsp"}]'::jsonb, 
    '[{"instruction": "Heat vegetable oil in a large pan or wok over medium-high heat."},{"instruction": "Add garlic and ginger, stir-fry for 30 seconds."},{"instruction": "Add chicken slices, stir-fry until cooked through."},{"instruction": "Add broccoli and bell pepper, stir-fry until tender-crisp."},{"instruction": "Stir in soy sauce, cook for another minute."},{"instruction": "Serve hot."}]'::jsonb, 
    '15 minutes', 
    '15 minutes', 
    '30 minutes', 
    '4', 
    '300', 
    '30g', 
    '15g', 
    '10g',
    'https://www.saltandlavender.com/wp-content/uploads/2022/03/chicken-stir-fry-1.jpg',
    'Main Courses',
    'Chinese'
  ),
  (
    'Classic Beef Lasagna', 
    '[{"ingredient": "lasagnaNoodles", "amount": "250g"},{"ingredient": "groundBeef", "amount": "500g"},{"ingredient": "onion", "amount": "1, chopped"},{"ingredient": "garlic", "amount": "2 cloves, minced"},{"ingredient": "tomatoSauce", "amount": "700ml"},{"ingredient": "mozzarellaCheese", "amount": "200g, grated"},{"ingredient": "ricottaCheese", "amount": "250g"},{"ingredient": "parmesanCheese", "amount": "50g, grated"},{"ingredient": "driedOregano", "amount": "1 tsp"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "pepper", "amount": "to taste"}]'::jsonb, 
    '[{"instruction": "Preheat oven to 180°C (350°F)."},{"instruction": "Cook lasagna noodles according to package instructions."},{"instruction": "In a large skillet, cook ground beef, onion, and garlic until beef is browned."},{"instruction": "Stir in tomato sauce, dried oregano, salt, and pepper. Simmer for 10 minutes."},{"instruction": "In a greased baking dish, layer noodles, meat sauce, ricotta cheese, and mozzarella cheese. Repeat layers."},{"instruction": "Top with grated Parmesan cheese."},{"instruction": "Bake in preheated oven for 30 minutes, until hot and bubbly."},{"instruction": "Let stand for 10 minutes before serving."}]'::jsonb, 
    '30 minutes', 
    '30 minutes', 
    '1 hour', 
    '6', 
    '500', 
    '35g', 
    '40g', 
    '20g',
    'https://www.recipegirl.com/wp-content/uploads/2021/04/Classic-Beef-Lasagna-8.jpeg',
    'Pasta',
    'Italian'
  ),
  (
    'Caesar Salad', 
    '[{"ingredient": "romaineLettuce", "amount": "1 head, torn into bite-size pieces"},{"ingredient": "croutons", "amount": "1 cup"},{"ingredient": "parmesanCheese", "amount": "50g, grated"},{"ingredient": "lemonJuice", "amount": "2 tbsp"},{"ingredient": "worcestershireSauce", "amount": "1 tsp"},{"ingredient": "dijonMustard", "amount": "1 tsp"},{"ingredient": "garlic", "amount": "1 clove, minced"},{"ingredient": "oliveOil", "amount": "3 tbsp"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "blackPepper", "amount": "to taste"}]'::jsonb, 
    '[{"instruction": "In a large salad bowl, whisk together lemon juice, Worcestershire sauce, Dijon mustard, garlic, olive oil, salt, and black pepper."},{"instruction": "Add torn romaine lettuce and toss to coat."},{"instruction": "Top with grated Parmesan cheese and croutons."},{"instruction": "Serve immediately."}]'::jsonb, 
    '15 minutes', 
    '0 minutes', 
    '15 minutes', 
    '4', 
    '250', 
    '8g', 
    '15g', 
    '18g',
    'https://natashaskitchen.com/wp-content/uploads/2019/01/Caesar-Salad-Recipe-3.jpg',
    'Salad',
    'Italian'
  ),
  (
    'Chocolate Chip Cookies', 
    '[{"ingredient": "butter", "amount": "200g, softened"},{"ingredient": "brownSugar", "amount": "200g"},{"ingredient": "granulatedSugar", "amount": "100g"},{"ingredient": "eggs", "amount": "2"},{"ingredient": "vanillaExtract", "amount": "2 tsp"},{"ingredient": "allPurposeFlour", "amount": "300g"},{"ingredient": "bakingSoda", "amount": "1 tsp"},{"ingredient": "salt", "amount": "1/2 tsp"},{"ingredient": "chocolateChips", "amount": "300g"}]'::jsonb, 
    '[{"instruction": "Preheat oven to 180°C (350°F)."},{"instruction": "In a large bowl, cream together butter, brown sugar, and granulated sugar until smooth."},{"instruction": "Beat in eggs and vanilla extract until fluffy."},{"instruction": "Combine flour, baking soda, and salt; gradually stir into the creamed mixture."},{"instruction": "Stir in chocolate chips."},{"instruction": "Drop by rounded teaspoonfuls onto ungreased cookie sheets."},{"instruction": "Bake for 10 to 12 minutes in preheated oven, or until edges are golden brown."},{"instruction": "Allow cookies to cool on baking sheet for 5 minutes before transferring to a wire rack to cool completely."}]'::jsonb, 
    '20 minutes', 
    '10 minutes', 
    '30 minutes', 
    '36 cookies', 
    '150', 
    '2g', 
    '20g', 
    '7g',
    'https://sallysbakingaddiction.com/wp-content/uploads/2013/05/classic-chocolate-chip-cookies.jpg',
    'Desserts',
    'American'
  ),
  (
    'Vegetarian Chili', 
    '[{"ingredient": "kidneyBeans", "amount": "400g can, drained and rinsed"},{"ingredient": "blackBeans", "amount": "400g can, drained and rinsed"},{"ingredient": "onion", "amount": "1, chopped"},{"ingredient": "bellPepper", "amount": "1, chopped"},{"ingredient": "carrots", "amount": "2, diced"},{"ingredient": "garlic", "amount": "2 cloves, minced"},{"ingredient": "chiliPowder", "amount": "2 tbsp"},{"ingredient": "cumin", "amount": "1 tbsp"},{"ingredient": "paprika", "amount": "1 tsp"},{"ingredient": "dicedTomatoes", "amount": "800g can"},{"ingredient": "vegetableStock", "amount": "500ml"},{"ingredient": "oliveOil", "amount": "2 tbsp"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "blackPepper", "amount": "to taste"}]'::jsonb, 
    '[{"instruction": "In a large pot, heat olive oil over medium heat."},{"instruction": "Add chopped onion, bell pepper, carrots, and garlic. Cook until softened, about 5 minutes."},{"instruction": "Stir in chili powder, cumin, and paprika. Cook for 1 minute until fragrant."},{"instruction": "Add diced tomatoes, vegetable stock, kidney beans, and black beans."},{"instruction": "Season with salt and pepper to taste."},{"instruction": "Bring to a boil, then reduce heat and simmer for 30 minutes, stirring occasionally."},{"instruction": "Serve hot, optionally garnished with sour cream, shredded cheese, and chopped cilantro."}]'::jsonb, 
    '15 minutes', 
    '45 minutes', 
    '1 hour', 
    '6', 
    '300', 
    '12g', 
    '50g', 
    '5g',
    'https://s23209.pcdn.co/wp-content/uploads/2022/10/211129_DAMN-DELICIOUS_Vegetarian-Chili_279.jpg',
    'Vegetarian',
    'Mexican'
  ),
  (
    'Margherita Pizza', 
    '[{"ingredient": "pizzaDough", "amount": "1 ball (store-bought or homemade)"},{"ingredient": "tomatoSauce", "amount": "200g"},{"ingredient": "freshMozzarellaCheese", "amount": "200g, sliced"},{"ingredient": "cherryTomatoes", "amount": "100g, halved"},{"ingredient": "freshBasilLeaves", "amount": "a handful"},{"ingredient": "oliveOil", "amount": "2 tbsp"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "blackPepper", "amount": "to taste"}]'::jsonb, 
    '[{"instruction": "Preheat oven to the highest temperature setting (usually around 250°C or 480°F)."},{"instruction": "Roll out pizza dough on a floured surface to desired thickness."},{"instruction": "Transfer dough to a pizza stone or baking sheet."},{"instruction": "Spread tomato sauce evenly over dough, leaving a small border around the edges."},{"instruction": "Arrange mozzarella slices and cherry tomato halves on top of sauce."},{"instruction": "Drizzle with olive oil and season with salt and black pepper."},{"instruction": "Bake in preheated oven for 10-12 minutes, until crust is golden and cheese is melted and bubbly."},{"instruction": "Remove from oven and top with fresh basil leaves before serving."}]'::jsonb, 
    '15 minutes', 
    '10 minutes', 
    '25 minutes', 
    '2-4', 
    '400', 
    '15g', 
    '45g', 
    '18g',
    'https://cookieandkate.com/images/2021/07/classic-margherita-pizza.jpg',
    'Baking',
    'Italian'
  ),
  (
    'Shrimp Tacos', 
    '[{"ingredient": "shrimp", "amount": "400g, peeled and deveined"},{"ingredient": "cabbage", "amount": "2 cups, shredded"},{"ingredient": "tortillas", "amount": "8 small"},{"ingredient": "limeJuice", "amount": "2 tbsp"},{"ingredient": "cumin", "amount": "1 tsp"},{"ingredient": "chiliPowder", "amount": "1 tsp"},{"ingredient": "garlicPowder", "amount": "1 tsp"},{"ingredient": "oliveOil", "amount": "2 tbsp"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "blackPepper", "amount": "to taste"},{"ingredient": "sourCream", "amount": "1/2 cup"}]'::jsonb, 
    '[{"instruction": "In a bowl, toss shrimp with lime juice, cumin, chili powder, garlic powder, salt, and black pepper."},{"instruction": "Heat olive oil in a skillet over medium heat. Cook shrimp until pink and opaque, about 2-3 minutes per side."},{"instruction": "Warm tortillas in a dry skillet or microwave."},{"instruction": "Assemble tacos by placing shrimp in tortillas, topping with shredded cabbage and a dollop of sour cream."},{"instruction": "Serve with lime wedges on the side."}]'::jsonb, 
    '10 minutes', 
    '10 minutes', 
    '20 minutes', 
    '4', 
    '250', 
    '20g', 
    '30g', 
    '8g',
    'https://www.cookingclassy.com/wp-content/uploads/2019/04/shrimp-tacos-1-500x500.jpg',
    'Seafood',
    'Mexican'
  ),
  (
    'Beef Stroganoff', 
    '[{"ingredient": "beefTenderloin", "amount": "500g, sliced into thin strips"},{"ingredient": "mushrooms", "amount": "250g, sliced"},{"ingredient": "onion", "amount": "1, chopped"},{"ingredient": "garlic", "amount": "2 cloves, minced"},{"ingredient": "beefBroth", "amount": "1 cup"},{"ingredient": "sourCream", "amount": "1 cup"},{"ingredient": "flour", "amount": "2 tbsp"},{"ingredient": "butter", "amount": "2 tbsp"},{"ingredient": "paprika", "amount": "1 tsp"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "blackPepper", "amount": "to taste"}]'::jsonb, 
    '[{"instruction": "Melt butter in a large skillet over medium heat."},{"instruction": "Add onion and garlic, cook until softened."},{"instruction": "Add mushrooms and cook until browned."},{"instruction": "Add beef strips and cook until browned."},{"instruction": "Sprinkle flour and paprika over the mixture, stir to combine."},{"instruction": "Gradually stir in beef broth, bring to a simmer."},{"instruction": "Stir in sour cream, cook until thickened."},{"instruction": "Season with salt and pepper to taste."},{"instruction": "Serve hot over egg noodles or rice."}]'::jsonb, 
    '15 minutes', 
    '20 minutes', 
    '35 minutes', 
    '4', 
    '450', 
    '30g', 
    '25g', 
    '20g',
    'https://www.simplyrecipes.com/thmb/xNFXADmB-zfgKKO3rA9Gfdmu_pQ=/2000x1500/filters:fill(auto,1)/Simply-Recipes-Beef-Stroganoff-LEAD-6-0b8bd0b6c6d1426798e4c7e91b14ef26.jpg',
    'Main Courses',
    'Russian'
  ),
  (
    'Tom Yum Soup', 
    '[{"ingredient": "shrimp", "amount": "300g, peeled and deveined"},{"ingredient": "lemongrass", "amount": "2 stalks, chopped"},{"ingredient": "galangal", "amount": "1 inch, sliced"},{"ingredient": "kaffirLimeLeaves", "amount": "3"},{"ingredient": "mushrooms", "amount": "200g, sliced"},{"ingredient": "cherryTomatoes", "amount": "100g, halved"},{"ingredient": "fishSauce", "amount": "2 tbsp"},{"ingredient": "limeJuice", "amount": "2 tbsp"},{"ingredient": "chilies", "amount": "3, crushed"},{"ingredient": "corianderLeaves", "amount": "a handful"},{"ingredient": "water", "amount": "4 cups"},{"ingredient": "salt", "amount": "to taste"}]'::jsonb, 
    '[{"instruction": "In a pot, bring water to a boil."},{"instruction": "Add lemongrass, galangal, kaffir lime leaves, and chilies. Simmer for 5 minutes."},{"instruction": "Add mushrooms and cherry tomatoes, cook for another 5 minutes."},{"instruction": "Add shrimp and cook until they turn pink and opaque."},{"instruction": "Stir in fish sauce and lime juice. Adjust seasoning with salt."},{"instruction": "Garnish with coriander leaves before serving."}]'::jsonb, 
    '10 minutes', 
    '15 minutes', 
    '25 minutes', 
    '4', 
    '200', 
    '18g', 
    '20g', 
    '5g',
    'https://www.recipetineats.com/wp-content/uploads/2019/03/Tom-Yum-Soup_2.jpg',
    'Soups',
    'Thai'
  ),
  -- Additional 40 Entries --
  (
    'Sushi Rolls', 
    '[{"ingredient": "sushiRice", "amount": "2 cups, cooked"},{"ingredient": "noriSheets", "amount": "6"},{"ingredient": "avocado", "amount": "1, sliced"},{"ingredient": "cucumber", "amount": "1, julienned"},{"ingredient": "carrots", "amount": "1, julienned"},{"ingredient": "soySauce", "amount": "for serving"},{"ingredient": "wasabi", "amount": "for serving"},{"ingredient": "pickledGinger", "amount": "for serving"}]'::jsonb, 
    '[{"instruction": "Place a bamboo sushi mat on a clean surface and cover it with plastic wrap."},{"instruction": "Lay a sheet of nori on the mat, shiny side down."},{"instruction": "Spread a thin layer of sushi rice over the nori, leaving a small border at the top."},{"instruction": "Arrange avocado, cucumber, and carrot strips along the bottom edge of the nori."},{"instruction": "Using the mat, roll the nori tightly around the fillings. Seal the edge with a little water."},{"instruction": "Slice the roll into bite-sized pieces using a sharp knife."},{"instruction": "Serve with soy sauce, wasabi, and pickled ginger."}]'::jsonb, 
    '20 minutes', 
    '0 minutes', 
    '20 minutes', 
    '4', 
    '250', 
    '6g', 
    '35g', 
    '8g',
    'https://www.justonecookbook.com/wp-content/uploads/2020/06/California-Roll-768x1152.jpg',
    'Seafood',
    'Japanese'
  ),
  (
    'Chicken Curry', 
    '[{"ingredient": "chickenBreast", "amount": "500g, cubed"},{"ingredient": "onion", "amount": "1, chopped"},{"ingredient": "garlic", "amount": "2 cloves, minced"},{"ingredient": "ginger", "amount": "1 inch, grated"},{"ingredient": "coconutMilk", "amount": "400ml"},{"ingredient": "curryPowder", "amount": "2 tbsp"},{"ingredient": "cumin", "amount": "1 tsp"},{"ingredient": "turmeric", "amount": "1 tsp"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "oil", "amount": "2 tbsp"}]'::jsonb, 
    '[{"instruction": "Heat oil in a large pot over medium heat."},{"instruction": "Add chopped onion, garlic, and ginger. Cook until softened."},{"instruction": "Stir in curry powder, cumin, and turmeric. Cook for 1 minute."},{"instruction": "Add chicken cubes and cook until browned."},{"instruction": "Pour in coconut milk, bring to a simmer."},{"instruction": "Season with salt and cook until chicken is cooked through."},{"instruction": "Serve hot with rice."}]'::jsonb, 
    '10 minutes', 
    '20 minutes', 
    '30 minutes', 
    '4', 
    '350', 
    '25g', 
    '10g', 
    '20g',
    'https://cafedelites.com/wp-content/uploads/2022/08/Chicken-Curry-2-4.jpg',
    'Main Courses',
    'Indian'
  ),
  (
    'Pancakes', 
    '[{"ingredient": "allPurposeFlour", "amount": "1 cup"},{"ingredient": "milk", "amount": "1 cup"},{"ingredient": "egg", "amount": "1"},{"ingredient": "butter", "amount": "2 tbsp, melted"},{"ingredient": "sugar", "amount": "2 tbsp"},{"ingredient": "bakingPowder", "amount": "2 tsp"},{"ingredient": "salt", "amount": "1/2 tsp"}]'::jsonb, 
    '[{"instruction": "In a large bowl, whisk together flour, sugar, baking powder, and salt."},{"instruction": "In another bowl, beat the egg and then whisk in milk and melted butter."},{"instruction": "Pour the wet ingredients into the dry ingredients and stir until just combined."},{"instruction": "Heat a lightly oiled griddle or frying pan over medium-high heat."},{"instruction": "Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake."},{"instruction": "Cook until pancakes are golden brown on both sides."},{"instruction": "Serve hot with syrup, butter, and fresh fruits."}]'::jsonb, 
    '5 minutes', 
    '10 minutes', 
    '15 minutes', 
    '4', 
    '150', 
    '4g', 
    '25g', 
    '5g',
    'https://www.recipetineats.com/wp-content/uploads/2017/06/Fluffy-Pancakes_5-SQ.jpg',
    'Breakfast',
    'American'
  ),
  (
    'Pad Thai', 
    '[{"ingredient": "riceNoodles", "amount": "200g"},{"ingredient": "shrimp", "amount": "200g, peeled and deveined"},{"ingredient": "beanSprouts", "amount": "1 cup"},{"ingredient": "tofu", "amount": "100g, cubed"},{"ingredient": "eggs", "amount": "2, beaten"},{"ingredient": "peanuts", "amount": "1/4 cup, crushed"},{"ingredient": "greenOnions", "amount": "2, chopped"},{"ingredient": "fishSauce", "amount": "3 tbsp"},{"ingredient": "tamarindPaste", "amount": "2 tbsp"},{"ingredient": "palmSugar", "amount": "1 tbsp"},{"ingredient": "chilies", "amount": "to taste"},{"ingredient": "lime", "amount": "1, cut into wedges"}]'::jsonb, 
    '[{"instruction": "Soak rice noodles in hot water until tender. Drain and set aside."},{"instruction": "In a wok or large skillet, heat oil over medium heat."},{"instruction": "Add tofu and cook until golden. Remove and set aside."},{"instruction": "Add shrimp and cook until pink. Remove and set aside."},{"instruction": "Pour beaten eggs into the wok and scramble."},{"instruction": "Add noodles, tofu, and shrimp back to the wok."},{"instruction": "Stir in fish sauce, tamarind paste, and palm sugar."},{"instruction": "Add bean sprouts and green onions, toss to combine."},{"instruction": "Serve hot, garnished with crushed peanuts and lime wedges."}]'::jsonb, 
    '10 minutes', 
    '15 minutes', 
    '25 minutes', 
    '4', 
    '400', 
    '20g', 
    '50g', 
    '15g',
    'https://www.recipetineats.com/wp-content/uploads/2018/03/Pad-Thai_0.jpg',
    'Main Courses',
    'Thai'
  ),
  (
    'Falafel', 
    '[{"ingredient": "chickpeas", "amount": "400g can, drained and rinsed"},{"ingredient": "onion", "amount": "1, chopped"},{"ingredient": "garlic", "amount": "3 cloves, minced"},{"ingredient": "parsley", "amount": "1 cup, chopped"},{"ingredient": "cilantro", "amount": "1 cup, chopped"},{"ingredient": "cumin", "amount": "1 tsp"},{"ingredient": "coriander", "amount": "1 tsp"},{"ingredient": "flour", "amount": "2 tbsp"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "blackPepper", "amount": "to taste"},{"ingredient": "oil", "amount": "for frying"}]'::jsonb, 
    '[{"instruction": "In a food processor, combine chickpeas, onion, garlic, parsley, cilantro, cumin, coriander, salt, and black pepper."},{"instruction": "Pulse until mixture is coarsely blended."},{"instruction": "Stir in flour to bind the mixture."},{"instruction": "Form mixture into small balls or patties."},{"instruction": "Heat oil in a skillet over medium-high heat."},{"instruction": "Fry falafel until golden brown on all sides."},{"instruction": "Drain on paper towels and serve hot with pita bread, tahini sauce, and salad."}]'::jsonb, 
    '10 minutes', 
    '10 minutes', 
    '20 minutes', 
    '4', 
    '250', 
    '10g', 
    '30g', 
    '10g',
    'https://www.recipetineats.com/wp-content/uploads/2018/06/Falafel_9.jpg',
    'Vegetarian',
    'Middle Eastern'
  ),
  (
    'Clam Chowder', 
    '[{"ingredient": "clams", "amount": "500g, cleaned"},{"ingredient": "potatoes", "amount": "2, diced"},{"ingredient": "onion", "amount": "1, chopped"},{"ingredient": "celery", "amount": "2 stalks, chopped"},{"ingredient": "carrots", "amount": "2, chopped"},{"ingredient": "bacon", "amount": "100g, diced"},{"ingredient": "butter", "amount": "2 tbsp"},{"ingredient": "flour", "amount": "2 tbsp"},{"ingredient": "milk", "amount": "2 cups"},{"ingredient": "heavyCream", "amount": "1 cup"},{"ingredient": "salt", "amount": "to taste"},{"ingredient": "blackPepper", "amount": "to taste"},{"ingredient": "thyme", "amount": "1 tsp"}]'::jsonb, 
    '[{"instruction": "In a large pot, cook bacon until crisp. Remove and set aside."},{"instruction": "In the same pot, melt butter and sauté onion, celery, and carrots until softened."},{"instruction": "Stir in flour and cook for 1 minute."},{"instruction": "Gradually stir in milk, heavy cream, and thyme. Bring to a simmer."},{"instruction": "Add potatoes and cook until tender."},{"instruction": "Stir in clams and bacon, season with salt and pepper."},{"instruction": "Serve hot with crusty bread."}]'::jsonb, 
    '15 minutes', 
    '30 minutes', 
    '45 minutes', 
    '4', 
    '400', 
    '15g', 
    '50g', 
    '20g',
    'https://www.recipetineats.com/wp-content/uploads/2018/06/Clam-Chowder_5.jpg',
    'Soups',
    'American'
  );
